version: '3.3'

services:
  web:
    image: nginx:latest
    restart: always
    ports:
      - '8080:80'
    volumes:
      - ./public:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html


  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cart


  sqlite:
    image: nouchka/sqlite3


